/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestsIndexRouteImport } from './routes/requests/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RequestsNewRouteImport } from './routes/requests/new'
import { Route as AdminWorkflowRouteImport } from './routes/admin/workflow'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminMasterDataRouteImport } from './routes/admin/master-data'
import { Route as AdminFormConfigRouteImport } from './routes/admin/form-config'
import { Route as AdminExportProfileRouteImport } from './routes/admin/export-profile'
import { Route as AdminAutofillRouteImport } from './routes/admin/autofill'
import { Route as RequestsRequestIdIndexRouteImport } from './routes/requests/$requestId/index'
import { Route as RequestsRequestIdHistoryRouteImport } from './routes/requests/$requestId/history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkflowRoute = AdminWorkflowRouteImport.update({
  id: '/admin/workflow',
  path: '/admin/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMasterDataRoute = AdminMasterDataRouteImport.update({
  id: '/admin/master-data',
  path: '/admin/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFormConfigRoute = AdminFormConfigRouteImport.update({
  id: '/admin/form-config',
  path: '/admin/form-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExportProfileRoute = AdminExportProfileRouteImport.update({
  id: '/admin/export-profile',
  path: '/admin/export-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAutofillRoute = AdminAutofillRouteImport.update({
  id: '/admin/autofill',
  path: '/admin/autofill',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRequestIdIndexRoute = RequestsRequestIdIndexRouteImport.update({
  id: '/requests/$requestId/',
  path: '/requests/$requestId/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRequestIdHistoryRoute =
  RequestsRequestIdHistoryRouteImport.update({
    id: '/requests/$requestId/history',
    path: '/requests/$requestId/history',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/autofill': typeof AdminAutofillRoute
  '/admin/export-profile': typeof AdminExportProfileRoute
  '/admin/form-config': typeof AdminFormConfigRoute
  '/admin/master-data': typeof AdminMasterDataRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflow': typeof AdminWorkflowRoute
  '/requests/new': typeof RequestsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/login/': typeof LoginIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/requests/$requestId/history': typeof RequestsRequestIdHistoryRoute
  '/requests/$requestId/': typeof RequestsRequestIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/autofill': typeof AdminAutofillRoute
  '/admin/export-profile': typeof AdminExportProfileRoute
  '/admin/form-config': typeof AdminFormConfigRoute
  '/admin/master-data': typeof AdminMasterDataRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflow': typeof AdminWorkflowRoute
  '/requests/new': typeof RequestsNewRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/history': typeof HistoryIndexRoute
  '/login': typeof LoginIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/requests/$requestId/history': typeof RequestsRequestIdHistoryRoute
  '/requests/$requestId': typeof RequestsRequestIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/autofill': typeof AdminAutofillRoute
  '/admin/export-profile': typeof AdminExportProfileRoute
  '/admin/form-config': typeof AdminFormConfigRoute
  '/admin/master-data': typeof AdminMasterDataRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflow': typeof AdminWorkflowRoute
  '/requests/new': typeof RequestsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/login/': typeof LoginIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/requests/$requestId/history': typeof RequestsRequestIdHistoryRoute
  '/requests/$requestId/': typeof RequestsRequestIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/autofill'
    | '/admin/export-profile'
    | '/admin/form-config'
    | '/admin/master-data'
    | '/admin/users'
    | '/admin/workflow'
    | '/requests/new'
    | '/admin/'
    | '/dashboard/'
    | '/history/'
    | '/login/'
    | '/requests/'
    | '/requests/$requestId/history'
    | '/requests/$requestId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/autofill'
    | '/admin/export-profile'
    | '/admin/form-config'
    | '/admin/master-data'
    | '/admin/users'
    | '/admin/workflow'
    | '/requests/new'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/requests'
    | '/requests/$requestId/history'
    | '/requests/$requestId'
  id:
    | '__root__'
    | '/'
    | '/admin/autofill'
    | '/admin/export-profile'
    | '/admin/form-config'
    | '/admin/master-data'
    | '/admin/users'
    | '/admin/workflow'
    | '/requests/new'
    | '/admin/'
    | '/dashboard/'
    | '/history/'
    | '/login/'
    | '/requests/'
    | '/requests/$requestId/history'
    | '/requests/$requestId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAutofillRoute: typeof AdminAutofillRoute
  AdminExportProfileRoute: typeof AdminExportProfileRoute
  AdminFormConfigRoute: typeof AdminFormConfigRoute
  AdminMasterDataRoute: typeof AdminMasterDataRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkflowRoute: typeof AdminWorkflowRoute
  RequestsNewRoute: typeof RequestsNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  RequestsRequestIdHistoryRoute: typeof RequestsRequestIdHistoryRoute
  RequestsRequestIdIndexRoute: typeof RequestsRequestIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workflow': {
      id: '/admin/workflow'
      path: '/admin/workflow'
      fullPath: '/admin/workflow'
      preLoaderRoute: typeof AdminWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/master-data': {
      id: '/admin/master-data'
      path: '/admin/master-data'
      fullPath: '/admin/master-data'
      preLoaderRoute: typeof AdminMasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/form-config': {
      id: '/admin/form-config'
      path: '/admin/form-config'
      fullPath: '/admin/form-config'
      preLoaderRoute: typeof AdminFormConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/export-profile': {
      id: '/admin/export-profile'
      path: '/admin/export-profile'
      fullPath: '/admin/export-profile'
      preLoaderRoute: typeof AdminExportProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/autofill': {
      id: '/admin/autofill'
      path: '/admin/autofill'
      fullPath: '/admin/autofill'
      preLoaderRoute: typeof AdminAutofillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$requestId/': {
      id: '/requests/$requestId/'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId/'
      preLoaderRoute: typeof RequestsRequestIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$requestId/history': {
      id: '/requests/$requestId/history'
      path: '/requests/$requestId/history'
      fullPath: '/requests/$requestId/history'
      preLoaderRoute: typeof RequestsRequestIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAutofillRoute: AdminAutofillRoute,
  AdminExportProfileRoute: AdminExportProfileRoute,
  AdminFormConfigRoute: AdminFormConfigRoute,
  AdminMasterDataRoute: AdminMasterDataRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkflowRoute: AdminWorkflowRoute,
  RequestsNewRoute: RequestsNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  RequestsRequestIdHistoryRoute: RequestsRequestIdHistoryRoute,
  RequestsRequestIdIndexRoute: RequestsRequestIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
